import { z } from 'zod';

const cities = [
    "New York, NY",
    "Los Angeles, CA",
    "Chicago, IL",
    "Miami, FL",
    "Houston, TX",
    "Dallas, TX",
    "Philadelphia, PA",
    "Atlanta, GA",
    "Washington, DC",
    "Boston, MA",
    "Phoenix, AZ",
    "Detroit, MI",
    "Seattle, WA",
    "San Francisco, CA",
    "San Diego, CA",
    "Minneapolis, MN",
    "Tampa, FL",
    "Brooklyn, NY",
    "Denver, CO",
    "Queens, NY",
    "Riverside, CA",
    "Las Vegas, NV",
    "Baltimore, MD",
    "St. Louis, MO",
    "Portland, OR",
    "San Antonio, TX",
    "Sacramento, CA",
    "Austin, TX",
    "Orlando, FL",
    "San Juan, PR",
    "San Jose, CA",
    "Indianapolis, IN",
    "Pittsburgh, PA",
    "Cincinnati, OH",
    "Manhattan, NY",
    "Kansas City, MO",
    "Cleveland, OH",
    "Columbus, OH",
    "Bronx, NY",
    "Charlotte, NC",
    "Virginia Beach, VA",
    "Jacksonville, FL",
    "Milwaukee, WI",
    "Providence, RI",
    "Nashville, TN",
    "Salt Lake City, UT",
    "Raleigh, NC",
    "Richmond, VA",
    "Memphis, TN",
    "Oklahoma City, OK",
    "Hartford, CT",
    "Louisville, KY",
    "Buffalo, NY",
    "Fort Worth, TX",
    "Bridgeport, CT",
    "New Orleans, LA",
    "Tucson, AZ",
    "El Paso, TX",
    "Omaha, NE",
    "McAllen, TX",
    "Birmingham, AL",
    "Albuquerque, NM",
    "Tulsa, OK",
    "Charleston, SC",
    "Fresno, CA",
    "Rochester, NY",
    "Dayton, OH",
    "Cape Coral, FL",
    "Provo, UT",
    "Colorado Springs, CO",
    "Mission Viejo, CA",
    "Allentown, PA",
    "Baton Rouge, LA",
    "Ogden, UT",
    "Knoxville, TN",
    "Grand Rapids, MI",
    "Columbia, SC",
    "Albany, NY",
    "Bakersfield, CA",
    "New Haven, CT",
    "Des Moines, IA",
    "Palm Bay, FL",
    "Akron, OH",
    "Concord, CA",
    "Mesa, AZ",
    "Wichita, KS",
    "Harrisburg, PA",
    "Staten Island, NY",
    "Toledo, OH",
    "Worcester, MA",
    "Port St. Lucie, FL",
    "Little Rock, AR",
    "Madison, WI",
    "Spokane, WA",
    "Long Beach, CA",
    "Denton, TX",
    "Reno, NV",
    "Boise, ID",
    "Bonita Springs, FL",
    "Kissimmee, FL",
    "Augusta, GA",
    "Springfield, MA",
    "Oakland, CA",
    "Winston-Salem, NC",
    "Stockton, CA",
    "Durham, NC",
    "Chattanooga, TN",
    "Greenville, SC",
    "Lancaster, PA",
    "Syracuse, NY",
    "Fayetteville, AR",
    "Pensacola, FL",
    "Arlington, TX",
    "Aurora, CO",
    "Scranton, PA",
    "Oxnard, CA",
    "Indio, CA",
    "Victorville, CA",
    "Trenton, NJ",
    "Huntsville, AL",
    "Modesto, CA",
    "Honolulu, HI",
    "Greensboro, NC",
    "Fort Wayne, IN",
    "Anaheim, CA",
    "Corpus Christi, TX",
    "Fort Collins, CO",
    "Antioch, CA",
    "Jackson, MS",
    "Fayetteville, NC",
    "Myrtle Beach, SC",
    "Henderson, NV",
    "Mobile, AL",
    "Lexington, KY",
    "Lansing, MI",
    "Savannah, GA",
    "Youngstown, OH",
    "Ann Arbor, MI",
    "Santa Ana, CA",
    "Irvine, CA",
    "St. Paul, MN",
    "Poughkeepsie, NY",
    "Newark, NJ",
    "Santa Rosa, CA",
    "Concord, NC",
    "Winter Haven, FL",
    "Asheville, NC",
    "Canton, OH",
    "Lincoln, NE",
    "Flint, MI",
    "Lakeland, FL",
    "Jersey City, NJ",
    "Anchorage, AK",
    "Springfield, MO",
    "Plano, TX",
    "Lubbock, TX",
    "Davenport, IA",
    "Reading, PA",
    "Shreveport, LA",
    "Chandler, AZ",
    "South Bend, IN",
    "Wilmington, NC",
    "Chula Vista, CA",
    "Rockford, IL",
    "Eugene, OR",
    "Salem, OR",
    "Gilbert, AZ",
    "North Las Vegas, NV",
    "Santa Clarita, CA",
    "Peoria, IL",
    "Tallahassee, FL",
    "Killeen, TX",
    "St. Petersburg, FL",
    "Kennewick, WA",
    "Columbus, GA",
    "Laredo, TX",
    "Irving, TX",
    "Round Lake Beach, IL",
    "Montgomery, AL",
    "Chesapeake, VA",
    "Glendale, AZ",
    "Nashua, NH",
    "York, PA",
    "Garland, TX",
    "Rock Hill, SC",
    "Scottsdale, AZ",
    "Aguadilla, PR",
    "Arlington, VA",
    "Norfolk, VA",
    "Appleton, WI",
    "Enterprise, NV",
    "Gulfport, MS",
    "Lafayette, LA",
    "Bremerton, WA",
    "Fremont, CA",
    "Green Bay, WI",
    "Fargo, ND",
    "Deltona, FL",
    "Brownsville, TX",
    "Hialeah, FL",
    "San Bernardino, CA",
    "Tacoma, WA",
    "Gainesville, FL",
    "Spring Valley, NV",
    "Clarksville, TN",
    "College Station, TX",
    "Olympia, WA",
    "Roanoke, VA",
    "Portland, ME",
    "Fontana, CA",
    "Spartanburg, SC",
    "Moreno Valley, CA",
    "Frisco, TX",
    "Yonkers, NY",
    "Thousand Oaks, CA",
    "Sioux Falls, SD",
    "Hagerstown, MD",
    "Evansville, IN",
    "Amarillo, TX",
    "Kalamazoo, MI",
    "Lorain, OH",
    "Galveston, TX",
    "McKinney, TX",
    "Huntington, WV",
    "Nampa, ID",
    "Hickory, NC",
    "Waterbury, CT",
    "Sunrise Manor, NV",
    "Grand Prairie, TX",
    "Ocala, FL",
    "Waco, TX",
    "Overland Park, KS",
    "Frederick, MD",
    "Huntington Beach, CA",
    "Santa Barbara, CA",
    "Peoria, AZ",
    "Cedar Rapids, IA",
    "Vancouver, WA",
    "Glendale, CA",
    "Gastonia, NC",
    "Spring Hill, FL",
    "Murfreesboro, TN",
    "Tempe, AZ",
    "Paradise, NV",
    "Newport News, VA",
    "Erie, PA",
    "Fort Lauderdale, FL",
    "Gainesville, GA",
    "Aurora, IL",
    "Mauldin, SC",
    "Ontario, CA",
    "Elk Grove, CA",
    "Panama City, FL",
    "Cary, NC",
    "Hemet, CA",
    "Danbury, CT",
    "Rancho Cucamonga, CA",
    "Salinas, CA",
    "Oceanside, CA",
    "Vallejo, CA",
    "High Point, NC",
    "Garden Grove, CA",
    "Pembroke Pines, FL",
    "Lancaster, CA",
    "Marysville, WA",
    "Bayamon, PR",
    "Fredericksburg, VA",
    "Visalia, CA",
    "Tuscaloosa, AL",
    "Palmdale, CA",
    "Santa Cruz, CA",
    "Medford, OR",
    "Norwich, CT",
    "Merced, CA",
    "Manchester, NH",
    "Odessa, TX",
    "Muskegon, MI",
    "Leesburg, FL",
    "Lafayette, IN",
    "Hayward, CA",
    "Corona, CA",
    "Paterson, NJ",
    "Alexandria, VA",
    "Macon, GA",
    "Lakewood, CO",
    "Springfield, IL",
    "Kansas City, KS",
    "Burlington, NC",
    "Warner Robins, GA",
    "Sunnyvale, CA",
    "Hollywood, FL",
    "Roseville, CA",
    "New Bedford, MA",
    "South Lyon, MI",
    "Bellevue, WA",
    "Fairfield, CA",
    "Binghamton, NY",
    "Topeka, KS",
    "Escondido, CA",
    "Joliet, IL",
    "Surprise, AZ",
    "Naperville, IL",
    "Pasadena, TX",
    "Mesquite, TX",
    "Champaign, IL",
    "Pomona, CA",
    "Houma, LA",
    "Athens, GA",
    "St. George, UT",
    "Beaumont, TX",
    "Elkhart, IN",
    "Lake Charles, LA",
    "Santa Maria, CA",
    "Yuma, AZ",
    "Olathe, KS",
    "Midland, TX",
    "Greeley, CO",
    "Torrance, CA",
    "Thornton, CO",
    "Las Cruces, NM",
    "Columbia, MO",
    "Fullerton, CA",
    "Grand Junction, CO",
    "Carolina, PR",
    "Metairie, LA",
    "Orange, CA",
    "Warren, MI",
    "West Valley City, UT",
    "Hampton, VA",
    "Pasadena, CA",
    "Miramar, FL",
    "Elizabeth, NJ",
    "Stamford, CT",
    "Racine, WI",
    "Kent, WA",
    "Yakima, WA",
    "Coral Springs, FL",
    "Sterling Heights, MI",
    "Billings, MT",
    "Bloomington, IL",
    "Charleston, WV",
    "Carrollton, TX",
    "Tyler, TX",
    "Iowa City, IA",
    "Johnson City, TN",
    "Santa Clara, CA",
    "Bellingham, WA",
    "Norman, OK",
    "Coeur d'Alene, ID",
    "Fort Smith, AR",
    "Lewisville, TX",
    "Dover, DE",
    "Yuba City, CA",
    "Lehigh Acres, FL",
    "Abilene, TX",
    "Simi Valley, CA",
    "Pearland, TX",
    "Kenosha, WI",
    "Arecibo, PR",
    "Meridian, ID",
    "Round Rock, TX",
    "Waldorf, MD",
    "Temple, TX",
    "Lynchburg, VA",
    "Rochester, MN",
    "Logan, UT",
    "Arvada, CO",
    "Clovis, CA",
    "Independence, MO",
    "Redding, CA",
    "Greenville, NC",
    "Duluth, MN",
    "Berkeley, CA",
    "Boulder, CO",
    "Pueblo, CO",
    "West Palm Beach, FL",
    "Burlington, VT",
    "Seaside, CA",
    "Richardson, TX",
    "Cambridge, MA",
    "Monroe, LA",
    "North Charleston, SC",
    "Saginaw, MI",
    "Clearwater, FL",
    "The Woodlands, TX",
    "Brandon, FL",
    "St. Cloud, MN",
    "West Jordan, UT",
    "Broken Arrow, OK",
    "Harlingen, TX",
    "Kailua, HI",
    "Westminster, CO",
    "Gilroy, CA",
    "Richmond, CA",
    "Mandeville, LA",
    "Utica, NY",
    "Ponce, PR",
    "League City, TX",
    "Port Arthur, TX",
    "Lowell, MA",
    "East Los Angeles, CA",
    "Carlsbad, CA",
    "Elgin, IL",
    "Waterloo, IA",
    "Leominster, MA",
    "Bend, OR",
    "Sioux City, IA",
    "Gresham, OR",
    "Longview, TX",
    "Pompano Beach, FL",
    "Downey, CA",
    "Murrieta, CA",
    "Idaho Falls, ID",
    "Miami Gardens, FL",
    "Everett, WA",
    "Holland, MI",
    "Costa Mesa, CA",
    "Temecula, CA",
    "Jacksonville, NC",
    "San Buenaventura, CA",
    "Sugar Land, TX",
    "Chico, CA",
    "South Fulton, GA",
    "Sparks, NV",
    "Eau Claire, WI",
    "Auburn, AL",
    "Dearborn, MI",
    "Riverview, FL",
    "Allen, TX",
    "West Covina, CA",
    "Centennial, CO",
    "Bloomington, IN",
    "Sandy Springs, GA",
    "El Monte, CA",
    "Hillsboro, OR",
    "Menifee, CA",
    "Rio Rancho, NM",
    "Davie, FL",
    "Jurupa Valley, CA",
    "Columbia, MD",
    "Inglewood, CA",
    "Spokane Valley, WA",
    "Renton, WA",
    "San Tan Valley, AZ",
    "Burbank, CA",
    "Brockton, MA",
    "El Cajon, CA",
    "Rialto, CA",
    "San Mateo, CA",
    "Goodyear, AZ",
    "Charlottesville, VA",
    "Lafayette, CO",
    "Lee's Summit, MO",
    "Edinburg, TX",
    "Daly City, CA",
    "Wichita Falls, TX",
    "Bowling Green, KY",
    "Longmont, CO",
    "Vacaville, CA",
    "Highlands Ranch, CO",
    "Quincy, MA",
    "Fishers, IN",
    "Lynn, MA",
    "Norwalk, CA",
    "Carmel, IN",
    "Hesperia, CA",
    "St. Augustine, FL",
    "Buckeye, AZ",
    "San Angelo, TX",
    "Federal Way, WA",
    "Bismarck, ND",
    "Boca Raton, FL",
    "New Braunfels, TX",
    "Vista, CA",
    "Beaverton, OR",
    "Portsmouth, VA",
    "Orem, UT",
    "Conroe, TX",
    "Suffolk, VA",
    "Sunrise, FL",
    "Lawrence, KS",
    "Arden-Arcade, CA",
    "Prescott Valley, AZ",
    "Middletown, OH",
    "San German, PR",
    "Edmond, OK",
    "Tracy, CA",
    "Manteca, CA",
    "Kingsport, TN",
    "Portsmouth, NH",
    "Sandy, UT",
    "Palm Coast, FL",
    "Slidell, LA",
    "San Marcos, CA",
    "Livonia, MI",
    "Santa Fe, NM",
    "Plantation, FL",
    "Atascocita, TX",
    "Fall River, MA"
];

export const CitySchema = z.enum(cities as [string, ...string[]]);

export type City = z.infer<typeof CitySchema>;